#!/usr/bin/env bash
# This script retrieves DNS information for specified subdomains of a given domain.

# Function to display information about subdomains
display_subdomain_info() {
    domain=$1
    subdomain=$2

    # If subdomain is not provided, set default subdomains to check
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    # Loop through subdomains
    for sub in "${subdomains[@]}"; do
        # Use dig command to get DNS information
        dns_info=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:')

        # Parse DNS information and display output
        if [ -n "$dns_info" ]; then
            record_type=$(echo "$dns_info" | awk 'NR==2{print $4}')
            destination=$(echo "$dns_info" | awk 'NR==2{print $5}')

            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

# Check if arguments are provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Call the function with provided arguments
display_subdomain_info "$@"
