#!/usr/bin/env bash
# This script installs nginx, removes the default index page, creates a new one, and restarts nginx

# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Remove the default nginx index page
sudo rm /var/www/html/index.nginx-debian.html

# Create a new index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart nginx
sudo service nginx restart
