#!/usr/bin/env bash
# This script creates a PID file, handles signals, and runs a loop.

# Create the PID file
echo $$ > /var/run/myscript.pid

# Trap SIGTERM, SIGINT, SIGQUIT signals and define custom actions
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 1' SIGTERM
trap 'echo "Y U no love me?!"; rm -f /var/run/myscript.pid; exit 1' SIGINT
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
